// <auto-generated />
using System;
using ClassificadorExtractorDocumentos.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClassificadorExtractorDocumentos.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DocFlowDbContext))]
    [Migration("20260718180311_AddSoftDeleteYAprobacionManual")]
    partial class AddSoftDeleteYAprobacionManual
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClassificadorExtractorDocumentos.Domain.Entities.FacturaLinea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("FacturaId")
                        .HasColumnType("int");

                    b.Property<decimal>("ImporteLinea")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NumLinea")
                        .HasColumnType("int");

                    b.Property<decimal>("PorcentajeIva")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.ToTable("FacturasLineas", (string)null);
                });

            modelBuilder.Entity("ClassificadorExtractorDocumentos.Domain.Entities.FacturaStaging", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseImponible")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CuotaIva")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("PendienteValidacion");

                    b.Property<DateTime?>("FechaAprobacionManual")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("FechaFactura")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaIngesta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateOnly?>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<string>("JsonOriginalExtraido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("EUR");

                    b.Property<byte>("NivelExtraccion")
                        .HasColumnType("tinyint");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<decimal?>("RetencionIrpf")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("ReverseCharge")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("RutaPdfOriginal")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId", "NumeroFactura")
                        .IsUnique()
                        .HasDatabaseName("UQ_Factura")
                        .HasFilter("[ProveedorId] IS NOT NULL AND [Estado] <> N'Rechazada' AND [FechaEliminacion] IS NULL");

                    b.ToTable("FacturasStaging", (string)null);
                });

            modelBuilder.Entity("ClassificadorExtractorDocumentos.Domain.Entities.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaAlta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Nif")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Nif")
                        .IsUnique();

                    b.ToTable("Proveedores", (string)null);
                });

            modelBuilder.Entity("ClassificadorExtractorDocumentos.Domain.Entities.ProveedorEjemplo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("JsonValidado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<string>("RutaImagen")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.ToTable("ProveedorEjemplos", (string)null);
                });

            modelBuilder.Entity("ClassificadorExtractorDocumentos.Domain.Entities.ValidacionIncidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("FacturaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.ToTable("ValidacionIncidencias", (string)null);
                });

            modelBuilder.Entity("ClassificadorExtractorDocumentos.Domain.Entities.FacturaLinea", b =>
                {
                    b.HasOne("ClassificadorExtractorDocumentos.Domain.Entities.FacturaStaging", "Factura")
                        .WithMany("Lineas")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("ClassificadorExtractorDocumentos.Domain.Entities.FacturaStaging", b =>
                {
                    b.HasOne("ClassificadorExtractorDocumentos.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany("Facturas")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("ClassificadorExtractorDocumentos.Domain.Entities.ProveedorEjemplo", b =>
                {
                    b.HasOne("ClassificadorExtractorDocumentos.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany("Ejemplos")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("ClassificadorExtractorDocumentos.Domain.Entities.ValidacionIncidencia", b =>
                {
                    b.HasOne("ClassificadorExtractorDocumentos.Domain.Entities.FacturaStaging", "Factura")
                        .WithMany("Incidencias")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("ClassificadorExtractorDocumentos.Domain.Entities.FacturaStaging", b =>
                {
                    b.Navigation("Incidencias");

                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("ClassificadorExtractorDocumentos.Domain.Entities.Proveedor", b =>
                {
                    b.Navigation("Ejemplos");

                    b.Navigation("Facturas");
                });
#pragma warning restore 612, 618
        }
    }
}
